### ISSUE TITLE
Check computing time for threading

### ISSUE THREAD

**Issue by mtceballos** [bcobo/SIRENA#2]
Check that computing time for threading or normal processing are really different

**Comment by bcobo** [comment]
Trabajando con dos ficheros (uno con sólo 10 records, file_10records.fits, y otro con ~8000 records, file1ph.fits) se comprueba que la reconstrucción sin threading es más rápida que si se hace con threading en ambos casos El comando que se corre en jupiter es:

_tesreconstruction Recordfile=file1ph.fits TesEventFile=evt_file1ph_NOthreading.fits Rcmethod=SIRENA PulseLength=8192 LibraryFile=library_file2_Kas_8192.fits samplesUp=3 nSgms=5 samplesDown=4 opmode=1 OFLib=yes FilterDomain=F detectionMode=STC Fitting35=3 FilterMethod=F0 clobber=yes EventListSize=1000 EnergyMethod=OPTFILT LagsOrNot=1 XMLFile=xifu_detector_lpa_75um_AR0.5_pixoffset_mux40_pitch275um.xml OFStrategy=FIXED OFLength=8192 filtEeV=5895.0_

Se ha de cambiar en hardware para que se corra con threading o no (en `scheduler.cpp`).

Se remite el problema a QUASAR y el problema era "Al hacer la reconstrucción del array final se estaba redimensionando constantemente. He hecho que el array sea del doble de tamaño que el número de records ya que en cada record hay entre 1 y 2 eventos detectados (al menos eso he visto). Se puede hacer más óptimo en términos de espacio y si en algún caso se detectan más de 2 eventos por record volvería a ir lento."

Se cambian las siguientes dos líneas de código:
_(*pulsesAll)->size = this->num_records;
(*pulsesAll)->pulses_detected = new PulseDetected[this→num_records];_

por las siguientes:
_(*pulsesAll)->size = this->num_records * 2;
(*pulsesAll)->pulses_detected = new PulseDetected[this->num_records * 2];_

Con la nueva versión de código se ha comprobado que la versión con threading tarda menos que sin threading . Se ha subido como 2.0.20.

**Comment by bcobo** [comment]
**Ojo con usar el comando clock() para calcular el tiempo de ejecución de un programa!!!**
_The clock() function in C++ returns the approximate processor time that is consumed by the program.
In order to compute the processor time, the difference between values returned by two different calls to clock(), one at the start and other at the end of the program is used. To convert the value to seconds, it needs to be divided by a macro CLOCKS_PER_SEC.
The clock() time may advance faster or slower than the actual wall clock. It depends on how the operating system allocates the resources for the process.
If the processor is shared by other processes, the clock() time may advance slower than the wall clock. While if the current process is executed in a multithreaded system, the clock() time may advance faster than wall clock._
Resultado: No usar clock() con threading

**Comment by mtceballos** [comment]
Solved.
